### ISSUE TITLE
E121: Undefined variable Hello'

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/neovim-prompt#11]
1. Copy `"Hello"` with `yy`
2. Open `:Denite file`
3. Paste it with `C-r + "`

```
[denite] Traceback (most recent call last):
[denite]   File "/Users/alisue/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/Users/alisue/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/Users/alisue/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 136, in _start
[denite]     status = self._prompt.start()
[denite]   File "/Users/alisue/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 201, in start
[denite]     raise e
[denite]   File "/Users/alisue/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 186, in start
[denite]     self.on_redraw()
[denite]   File "/Users/alisue/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 245, in on_redraw
[denite]     self.redraw_prompt()
[denite]   File "/Users/alisue/.cache/dein/.cache/init.vim/.dein/rplugin/python3/denite/prompt/prompt.py", line 164, in redraw_prompt
[denite]     build_echon_expr(forward_text, self.highlight_text),
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 272, in command
[denite]     return self.request('nvim_command', string, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
[denite]     raise self.error_wrapper(err)
[denite] neovim.api.nvim.NvimError: b'Vim(echon):E121: Undefined variable: Hello'
[denite] Please execute :messages command.
```

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/neovim-prompt/blob/master/util.py#L192

`term` is not escaped that's why.

**Comment by lambdalisue** [comment]
Fixed with https://github.com/lambdalisue/neovim-prompt/commit/918283d22f74bdfd95a709849223e40c7b5fe1f8
